bin: checkout: fail when REPO does not exist and does not end with .git

diff --git a/bin/checkout b/bin/checkout
--- a/bin/checkout
+++ b/bin/checkout
@@ -5,6 +5,11 @@ BRANCH="$2"
 
 if [ ! -d "$HOME/repos/git/$REPO" ]
 then
+  if [ "${REPO%.git}" = "$REPO" ]
+  then
+    echo "Error: expected $REPO to be a git source specifier that ends with .git" 1>&2
+    exit 1
+  fi
   URL="$REPO"
   REPO="${REPO##*/}"
   REPO="${REPO%.git}"
