bin: checkout: abort if the directory already exists

diff --git a/bin/checkout b/bin/checkout
--- a/bin/checkout
+++ b/bin/checkout
@@ -8,6 +8,12 @@ then
   REPO="${REPO##*/}"
 fi
 
+if [ -e "$REPO" ]
+then
+  echo "Cannot checkout, folder $REPO already exists"
+  exit 1
+fi
+
 if [ -n "$2" ]
 then
   BRANCH="$2"
