bin: co: fail if branch not given

diff --git a/bin/co b/bin/co
--- a/bin/co
+++ b/bin/co
@@ -2,6 +2,13 @@
 
 REPO="$1"
 BRANCH="$2"
+
+if [ -z "$BRANCH" ]
+then
+  echo "Error: no branch specified in arguments" 1>&2
+  exit 1
+fi
+
 DIR="$(sanitize "$BRANCH")"
 
 mkdir --parents "$DIR" && cd "$DIR" && checkout "$REPO" "$BRANCH" "$@"
