gitD: use git-annex to sync .varia/irssi

diff --git a/bin/gitD b/bin/gitD
--- a/bin/gitD
+++ b/bin/gitD
@@ -9,7 +9,8 @@ done
 
 if [ -e "$HOME/.varia/irssi" ]
 then
-    rdiff-backup jakut.is::.irssi "$HOME/.varia/irssi"
+    cd "$HOME/.varia/irssi"
+    git annex sync && git annex get . || echo ".varia/irssi sync failed" && exit 1
 fi
 
 for A in .varia/albums .varia/gajim .Skype bin Maildir .osmo .gnupg .winetrickscache .varia/minecraft .varia/albums .varia/dokuwiki .varia/ejabberd .varia/log .varia/maildir .varia/wiki.lanparty.lt etc/gitolite-admin .varia/ssl .varia/gramps .varia/zotero-dav .varia/wordpress .varia/linklog etc/latex .varia/thinkup .varia/zotero-main .varia/zotero-dataserver etc/r etc/blog etc/base etc/wiki .varia/piwigo etc/gitolite-admin-codingsummit.com
