bin: repos-up: hg: drop the first tag which is always "tip"

diff --git a/bin/repos-up b/bin/repos-up
--- a/bin/repos-up
+++ b/bin/repos-up
@@ -25,7 +25,12 @@ do
                 hg pull 1>/dev/null || exit 1
                 hg update 1>/dev/null || exit 1
                 hg tags | diff -ru "$CFG/$TYPE/$REPO" -
-                hg tags > "$CFG/$TYPE/$REPO"
+                if [ "$(hg tags|head -n 1)" != "tip" ]
+                then
+                    echo "Error: expected "tip" to be the first tag" 1>&2
+                    exit 1
+                fi
+                hg tags | tail -n +2 > "$CFG/$TYPE/$REPO"
                 ;;
             "git")
                 git fetch --all --tags 1>/dev/null 2>&1 || exit 1
