bin: root: rm: do not exit after first failure

diff --git a/bin/root b/bin/root
--- a/bin/root
+++ b/bin/root
@@ -306,7 +306,7 @@ function command_rm {
   do
     FULL_PATH="$(realpath --canonicalize-missing "$ORIGINAL_DIR/${1}")"
     SOURCE=".${FULL_PATH:${#ROOT_DIR}}"
-    echo "removing $SOURCE" && dav_delete "$SOURCE" || exit 1
+    echo "removing $SOURCE" && (dav_delete "$SOURCE") || echo failed
     shift
   done
 }
