bin: syncmediaplayer: move NAME and SOURCE from config to cli arguments

diff --git a/bin/syncmediaplayer b/bin/syncmediaplayer
--- a/bin/syncmediaplayer
+++ b/bin/syncmediaplayer
@@ -6,8 +6,6 @@ if ! [ -e "$CFG" ]
 then
     echo "Please create a config file "$CFG""
     echo "Example:"
-    echo "sansasd"
-    echo "/mnt/media/music"
     echo "MUS /albums-flac/1957 - Ella Fitzgerald, Billie Holiday, And Carmen McRae at Newport"
     echo "POD /podcasts/somafm"
     echo "MUS /albums-flac/Wild Nothing - Nocturne (2012) [FLAC]"
@@ -21,28 +19,31 @@ then
     exit 1
 fi
 
+NAME="$2"
+if [ -z "$NAME" ]
+then
+    echo "Error: please specify the media player name (must be mounted on /mnt/<name>)" >&2
+    exit 1
+fi
+
+SOURCE="$3"
+if [ -z "$SOURCE" ]
+then
+    echo "Error: please specify the root directory of files" >&2
+    exit 1
+fi
+
+if ! [ -d "$SOURCE" ]
+then
+    echo "Error: the specified root directory of files does not exist: $SOURCE"
+    exit 1
+fi
+
+mymount "$NAME" || exit 1
 
 cat "$CFG" | (
-I=0
 while read ITEM
 do
-    I=$(($I + 1))
-    if [ "$I" = "1" ]
-    then
-        NAME="$ITEM"
-        mymount "$NAME" || exit 1
-        continue
-    fi
-    if [ "$I" = "2" ]
-    then
-        SOURCE="$ITEM"
-        if ! [ -d "$SOURCE" ]
-        then
-            echo "Source directory "$SOURCE" does not exist"
-            exit 1
-        fi
-        continue
-    fi
     echo $ITEM
 
     DIR="${ITEM:4}"
@@ -56,7 +57,14 @@ do
         TARGET="/MUSIC/PODCASTS"
     fi
 
+    if ! [ -d "$SOURCE$DIR" ]
+    then
+        echo "A source directory $SOURCE$DIR does not exist"
+        exit 1
+    fi
+
     cd "$SOURCE$DIR"
+
     /usr/bin/find . -mtime "-$DAYS" | (while read FILE
     do
         if [ -d "$FILE" ]
