bin: syncmediaplayer: convert media player directory and root directory to absolute path

diff --git a/bin/syncmediaplayer b/bin/syncmediaplayer
--- a/bin/syncmediaplayer
+++ b/bin/syncmediaplayer
@@ -30,6 +30,7 @@ then
     echo "Error: media player directory $ROOT does not exist" >&2
     exit 1
 fi
+ROOT="$(realpath "$ROOT")"
 
 SOURCE="$3"
 if [ -z "$SOURCE" ]
@@ -37,12 +38,12 @@ then
     echo "Error: please specify the root directory of files" >&2
     exit 1
 fi
-
 if ! [ -d "$SOURCE" ]
 then
     echo "Error: the specified root directory of files does not exist: $SOURCE"
     exit 1
 fi
+SOURCE="$(realpath "$SOURCE")"
 
 cat "$CFG" | (
 while read ITEM
@@ -62,7 +63,7 @@ do
 
     if ! [ -d "$SOURCE$DIR" ]
     then
-        echo "A source directory $SOURCE$DIR does not exist"
+        echo "Error: A source directory \"$SOURCE$DIR\" does not exist" >&2
         exit 1
     fi
 
