bin: system: vpn: handle unknown command case

diff --git a/bin/system b/bin/system
--- a/bin/system
+++ b/bin/system
@@ -297,6 +297,9 @@ case "$CMD" in
         elif [ "$2" = "stop" ]
         then
           stop_vpn
+        else
+          echo "Error: unknown vpn command \"$2\""
+          exit 1
         fi
         ;;
     "keyboard")
