bin: www: check for chrome before chromium

diff --git a/bin/www b/bin/www
--- a/bin/www
+++ b/bin/www
@@ -2,22 +2,18 @@
 
 FLAGS="--user-data-dir="$HOME/.config/google-chrome" --enable-experimental-extension-apis --ignore-gpu-blacklist --audio-buffer-size=4096"
 
-BROWSER="$(which chromium-browser 2>/dev/null)"
-if [ -z "$BROWSER" ]
-then
-    BROWSER="$(which chrome 2>/dev/null)"
-fi
-if [ -z "$BROWSER" ]
-then
-    BROWSER="$(which google-chrome 2>/dev/null)"
-fi
-if [ -z "$BROWSER" ]
-then
-    BROWSER="$(which chromium 2>/dev/null)"
-fi
-if [ -z "$BROWSER" ]
-then
-    BROWSER="$(which google-chrome-stable 2>/dev/null)"
-fi
+for BIN in google-chrome-stable google-chrome chrome chromium-browser chromium
+do
+    BROWSER="$(which "$BIN" 2>/dev/null)"
+    if [ -n "$BROWSER" ]
+    then
+        break
+    fi
+done
 
+if [ -z "$BROWSER" ]
+then
+    echo "Error: chrome or chromium not found" 1>&2
+    exit 1
+fi
 "$BROWSER" $FLAGS "$1" 2>/dev/null 1>/dev/null
